create table clients (
	client_id INT NOT NULL PRIMARY KEY,
	cname VARCHAR(50),
	csurame VARCHAR(50),
	cstreet  VARCHAR(50),
	czip VARCHAR(50),
	ccity VARCHAR(50),
	country_name VARCHAR(52) REFERENCES countries(country_name),
	cemail VARCHAR(50),
	cphone VARCHAR(50),
	c_spec_request TEXT
);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (1, 'Minnaminnie', 'Coard', 'Carey', null, 'Barajevo', 'Japan', 'mcoard0@usnews.com', null, null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (2, 'Merissa', 'Chin', null, null, null, null, null, '+63 742 899 6112', 'Ergonomic motivating software');
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (3, 'Standford', 'De Benedictis', null, null, null, null, null, '+229 244 954 5296', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (4, 'Ardelis', 'Reach', 'Oak Valley', null, 'Kabalo', 'Turks and Caicos Islands', 'areach3@prweb.com', '+242 375 900 7844', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (5, 'Sharla', 'Barette', null, null, null, null, null, '+62 487 147 1836', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (6, 'Lesley', 'Worge', 'Armistice', null, 'Kokkári', 'United Kingdom of Great Britain and Northern Ireland', 'lworge5@alibaba.com', '+30 203 867 2579', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (7, 'Joelynn', 'Pettigrew', 'Clarendon', '37-114', 'Białobrzegi', 'Myanmar', 'jpettigrew6@topsy.com', '+48 296 575 4280', 'Programmable tertiary initiative');
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (8, 'Waldon', 'Liverseege', 'Arkansas', null, 'Dashu', 'Lao People''s Democratic Republic', 'wliverseege7@indiatimes.com', '+86 107 627 5406', 'Programmable executive initiative');
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (9, 'Dex', 'Harbar', 'Bluejay', '301573', 'Lomintsevskiy', 'Namibia', 'dharbar8@sciencedirect.com', '+7 120 390 3171', 'Future-proofed cohesive budgetary management');
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (10, 'Suellen', 'Milsap', 'Hauk', '2775-389', 'Rana', 'Central African Republic', 'smilsap9@weebly.com', '+351 269 705 7294', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (11, 'Filmer', 'Muddle', 'Ramsey', '230029', 'Montería', 'Western Sahara', 'fmuddlea@netvibes.com', '+57 441 189 3208', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (12, 'Shell', null, null, null, null, null, null, '+242 853 839 6627', 'Synergistic mission-critical strategy');
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (13, 'Bartel', 'Burgen', null, null, null, null, null, '+7 665 358 2552', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (14, 'Lazaro', null, 'Shopko', '618383', 'Shakhta', 'Macao', 'lrobbingsd@hhs.gov', '+7 758 572 8113', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (15, 'Harald', null, 'Twin Pines', '658540', 'Rebrikha', 'China', 'hpitsalle@illinois.edu', '+7 732 952 9710', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (16, 'Niels', 'Sabate', null, null, null, null, null, '+30 228 714 1068', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (17, 'Vanya', 'Sothcott', 'Marcy', '9213', 'Babug', 'Greece', 'vsothcottg@flickr.com', '+63 157 447 9730', 'Right-sized homogeneous infrastructure');
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (18, 'Paolo', 'Samwyse', 'La Follette', null, 'Garoua Boulaï', 'Antarctica', 'psamwyseh@ftc.gov', '+237 547 820 1287', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (19, 'Phylys', 'Hembery', null, null, null, null, null, '+55 496 631 2337', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (20, 'Reinaldo', 'Triggle', 'Tennessee', '97-216', 'Czerniewice', 'Latvia', 'rtrigglej@opera.com', '+48 202 317 7988', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (21, 'Ruby', 'Tolhurst', null, null, null, null, null, '+86 725 692 6499', 'Innovative radical application');
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (22, 'Baxter', 'Scahill', 'Stephen', null, 'Bangbayang', 'Cocos (Keeling) Islands', 'bscahilll@istockphoto.com', '+62 469 410 0106', 'Reactive zero administration product');
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (23, 'Maynard', 'Marquand', null, null, null, null, null, '+351 722 688 2684', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (24, 'Sanford', 'Gallifont', null, null, null, null, null, '+7 247 388 0969', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (25, 'Alvy', 'Rilton', null, null, null, null, null, '+33 529 776 0742', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (26, 'Antin', 'Hayhurst', null, null, null, null, null, '+30 542 835 6919', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (27, 'Maribel', 'Gorrissen', 'Alpine', null, 'Kertasari', 'Yemen', 'mgorrissenq@illinois.edu', '+62 976 142 5467', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (28, 'Frankie', 'MacDearmid', null, null, null, null, null, '+86 459 281 0077', 'Seamless upward-trending website');
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (29, 'Shirl', 'Truce', 'Ronald Regan', '0654', 'Oslo', 'Paraguay', 'struces@livejournal.com', '+47 657 880 4555', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (30, 'Odessa', 'Reckless', null, null, null, null, null, '+30 494 540 9373', 'Public-key multimedia conglomeration');
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (31, 'Pearce', 'Marran', 'Ohio', '617071', 'Overyata', 'Ethiopia', 'pmarranu@devhub.com', '+7 219 965 4785', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (32, 'Giffie', 'Fridaye', null, null, null, null, null, '+86 197 373 0900', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (33, 'Shermie', 'Hayfield', 'Banding', null, 'Pohonsirih', 'Niger', 'shayfieldw@wikimedia.org', '+62 348 267 9360', 'User-centric bandwidth-monitored standardization');
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (34, 'Elka', 'Dimond', 'Sutteridge', null, 'Fatumnasi', 'United States of America', 'edimondx@google.com.au', '+62 881 967 5151', 'Adaptive zero defect system engine');
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (35, 'Lucila', 'Bethell', null, null, null, null, null, '+86 264 115 0407', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (36, 'Jeremy', 'Swan', 'Burning Wood', '62601', 'Lappajärvi', 'Colombia', 'jswanz@infoseek.co.jp', '+358 396 753 3208', 'Triple-buffered contextually-based contingency');
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (37, 'Pail', 'Boyle', '5th', null, 'Kuanghe', 'Western Sahara', 'pboyle10@ebay.co.uk', '+86 934 695 9636', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (38, 'Norina', 'Moughtin', 'Cardinal', '7945', 'Rosebank', 'French Polynesia', 'nmoughtin11@umich.edu', '+27 593 795 1510', 'Sharable modular moratorium');
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (39, 'Malvina', null, 'Vahlen', '89862-000', 'Entre Rios', 'Belgium', 'mdominka12@tumblr.com', '+55 982 519 0073', 'Switchable impactful contingency');
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (40, 'Ryun', 'Haggata', null, null, null, null, null, '+1 570 870 1230', 'Polarised systemic leverage');
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (41, 'Addie', 'Naismith', 'Maywood', null, 'Hengjie', 'Canada', 'anaismith14@icq.com', '+86 390 426 9670', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (42, 'Aimil', 'Smeed', null, null, null, null, null, '+48 316 174 7932', 'Implemented object-oriented analyzer');
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (43, 'Shermy', 'Jeanequin', null, null, null, null, null, '+509 870 339 7225', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (44, 'Niels', 'Kellie', 'Bellgrove', null, 'Boneng', 'Burundi', 'nkellie17@whitehouse.gov', '+62 357 320 3431', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (45, 'Cassie', 'Sorsby', 'Menomonie', null, 'Ilandža', 'Timor-Leste', 'csorsby18@blog.com', '+381 495 190 0166', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (46, 'Davie', 'Nickell', null, null, null, null, null, '+86 506 742 6980', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (47, 'Damita', 'Hegge', 'Elka', null, 'Banyubang', 'Maldives', 'dhegge1a@e-recht24.de', '+62 219 477 7137', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (48, 'Emmy', 'Botcherby', 'Union', '3153', 'Victoria', 'Samoa', 'ebotcherby1b@sbwire.com', '+54 998 276 9507', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (49, 'Langsdon', 'Prydden', 'Carberry', '142145', 'Rakhmanovo', 'Falkland Islands (Malvinas)', 'lprydden1c@goo.gl', '+7 243 552 4307', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (50, 'Bertrand', null, 'Forest', '456875', 'Kyshtym', 'Austria', 'bgrigoli1d@google.com', '+7 355 553 0474', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (51, 'Karlee', 'Mc Faul', null, null, null, null, null, '+86 673 396 4620', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (52, 'Richmond', 'Tomkins', 'Iowa', '242622', 'Lyubokhna', 'Gabon', 'rtomkins1f@google.com.br', '+7 232 507 7386', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (53, 'Grace', 'Goodge', null, null, null, null, null, '+385 129 200 5484', 'Extended mission-critical portal');
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (54, 'Gayleen', 'Mallindine', 'Namekagon', '76-220', 'Główczyce', 'Slovenia', 'gmallindine1h@discuz.net', '+48 674 244 8480', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (55, 'Carissa', 'Elsop', null, null, null, null, null, '+93 179 471 4563', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (56, 'Ivette', 'Brenneke', 'Quincy', null, 'Gengwan', 'Sudan', 'ibrenneke1j@purevolume.com', '+86 400 267 4967', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (57, 'Cathi', 'Kohrsen', 'Rieder', '538 63', 'Chroustovice', 'San Marino', 'ckohrsen1k@home.pl', '+420 571 640 8121', 'Sharable 4th generation access');
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (58, 'Mahalia', 'Mapes', null, null, null, null, null, '+255 608 735 6786', 'Pre-emptive motivating collaboration');
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (59, 'Bryn', 'Hance', null, null, null, null, null, '+31 568 945 3227', 'Fully-configurable secondary task-force');
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (60, 'Francine', 'Vedishchev', null, null, null, null, null, '+593 124 197 7048', 'Enterprise-wide mobile alliance');
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (61, 'Vitia', 'Gettings', 'South', '6219', 'Caticugan', 'Pakistan', 'vgettings1o@dropbox.com', '+63 914 804 7742', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (62, 'Gavan', 'Hailston', 'Sheridan', null, 'Bucu Lor', 'Mozambique', 'ghailston1p@blogspot.com', '+62 509 314 5702', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (63, 'Lissa', 'Gorden', 'Roxbury', '69-101', 'Słubice', 'French Guiana', 'lgorden1q@alexa.com', '+48 194 624 7759', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (64, 'Gretal', 'Pealing', 'Raven', null, 'Yataity del Norte', 'Palau', 'gpealing1r@fda.gov', '+595 209 134 9391', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (65, 'Anson', null, 'Donald', null, 'Venilale', 'Gabon', 'aherity1s@exblog.jp', '+670 557 372 2313', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (66, 'Tatiania', 'Drieu', 'Tony', null, 'Sūrak', 'Belgium', 'tdrieu1t@behance.net', '+98 166 128 4845', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (67, 'Kerri', 'Partner', null, null, null, null, null, '+86 853 550 1895', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (68, 'Adler', 'Deppe', 'Dahle', null, 'Ngurenrejo', 'Bulgaria', 'adeppe1v@reference.com', '+62 977 690 1729', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (69, 'Worth', 'Bisgrove', 'Corscot', null, 'Derbur', 'Brunei Darussalam', 'wbisgrove1w@globo.com', '+86 750 186 1384', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (70, 'Noellyn', 'Dewen', null, null, null, null, null, '+62 582 340 9570', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (71, 'Reg', null, null, null, null, null, null, '+81 610 491 0651', 'Synergistic systemic internet solution');
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (72, 'Benedetta', 'Schubuser', null, null, null, null, null, '+55 514 767 4851', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (73, 'Fernanda', 'Ghelardi', null, null, null, null, null, '+51 922 968 9371', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (74, 'Brandtr', 'Bourges', null, null, null, null, null, '+58 716 271 5651', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (75, 'Abigael', 'Gauvain', null, null, null, null, null, '+352 634 796 4575', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (76, 'Kleon', 'Carss', null, null, null, null, null, '+351 966 422 4052', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (77, 'Louis', 'Pidgeley', null, null, null, null, null, '+47 157 505 0096', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (78, 'Parsifal', 'Cullerne', 'Debra', '664 64', 'Dolní Kounice', 'Chad', 'pcullerne25@gmpg.org', '+420 400 698 6200', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (79, 'Daisey', 'Webberley', null, null, null, null, null, '+351 550 359 8984', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (80, 'Meryl', 'Doram', 'Summit', null, 'Lianhe', 'Saint Vincent and the Grenadines', 'mdoram27@sitemeter.com', '+86 227 523 7297', 'Progressive composite challenge');
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (81, 'Gabrila', 'Sealeaf', null, null, null, null, null, '+86 984 512 6383', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (82, 'Marline', 'Baldetti', null, null, null, null, null, '+51 901 143 7664', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (83, 'Umberto', 'Kelloway', null, null, null, null, null, '+420 414 153 1535', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (84, 'Doralynn', 'Silwood', 'Northridge', 'MD-6242', 'Biruinţa', 'Ghana', 'dsilwood2b@shutterfly.com', '+373 390 979 2506', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (85, 'Andria', 'Hyde-Chambers', null, null, null, null, null, '+7 352 508 6687', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (86, 'Rea', 'Kirvell', '3rd', null, 'Lysychovo', 'Vanuatu', 'rkirvell2d@lulu.com', '+380 872 663 1975', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (87, 'Dan', 'Mendes', null, null, null, null, null, '+93 248 623 5109', 'Business-focused modular data-warehouse');
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (88, 'Ramona', 'Kidson', null, null, null, null, null, '+55 515 876 4085', 'Mandatory client-driven array');
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (89, 'Margarethe', null, 'Utah', null, 'Tanjung Raja', 'Pakistan', 'mtommis2g@about.me', '+62 709 911 5416', 'Extended executive framework');
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (90, 'Egan', null, null, null, null, null, null, '+62 735 235 8913', 'Triple-buffered regional concept');
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (91, 'Quintilla', null, null, null, null, null, null, '+7 732 590 5446', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (92, 'Nikki', 'Bebbell', 'Wayridge', null, 'Oof', 'Uruguay', 'nbebbell2j@yandex.ru', '+62 351 213 6506', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (93, 'Rudolfo', 'Eakens', null, null, null, null, null, '+86 432 711 9026', 'Optional dedicated software');
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (94, 'Cirillo', null, 'Vernon', null, 'Urung', 'Malawi', 'cbatie2l@mozilla.org', '+62 861 248 7880', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (95, 'Quintina', null, 'Delladonna', null, 'Khanabad', 'Lithuania', 'qvanrembrandt2m@ustream.tv', '+93 420 643 1534', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (96, 'Wright', 'Bernt', 'Northwestern', null, 'Dahedian', 'Sweden', 'wbernt2n@friendfeed.com', '+86 346 262 8531', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (97, 'Cal', 'Marzellano', 'Morning', '73700-000', 'Padre Bernardo', 'Tonga', 'cmarzellano2o@goo.ne.jp', '+55 375 737 6136', 'Persistent optimal project');
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (98, 'Edee', 'Tumilty', null, null, null, null, null, '+351 408 425 0059', 'Public-key regional encryption');
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (99, 'Quintina', 'Loade', null, null, null, null, null, '+44 238 409 5089', null);
insert into clients (client_id, cname, csurame, cstreet , czip, ccity, country_name, cemail, cphone, c_spec_request) values (100, 'Lorita', 'Zanolli', 'Arizona', null, 'Quartier Morin', 'Lebanon', 'lzanolli2r@pbs.org', '+509 129 790 9794', 'Universal empowering circuit');
