create table countries (
	country_name VARCHAR(52) NOT NULL PRIMARY KEY,
	iso_c_code VARCHAR(2)
);
insert into countries (country_name, iso_c_code) values ('Afghanistan', 'AF');
insert into countries (country_name, iso_c_code) values ('Åland Islands', 'AX');
insert into countries (country_name, iso_c_code) values ('Albania', 'AL');
insert into countries (country_name, iso_c_code) values ('Algeria', 'DZ');
insert into countries (country_name, iso_c_code) values ('American Samoa', 'AS');
insert into countries (country_name, iso_c_code) values ('Andorra', 'AD');
insert into countries (country_name, iso_c_code) values ('Angola', 'AO');
insert into countries (country_name, iso_c_code) values ('Anguilla', 'AI');
insert into countries (country_name, iso_c_code) values ('Antarctica', 'AQ');
insert into countries (country_name, iso_c_code) values ('Antigua and Barbuda', 'AG');
insert into countries (country_name, iso_c_code) values ('Argentina', 'AR');
insert into countries (country_name, iso_c_code) values ('Armenia', 'AM');
insert into countries (country_name, iso_c_code) values ('Aruba', 'AW');
insert into countries (country_name, iso_c_code) values ('Australia', 'AU');
insert into countries (country_name, iso_c_code) values ('Austria', 'AT');
insert into countries (country_name, iso_c_code) values ('Azerbaijan', 'AZ');
insert into countries (country_name, iso_c_code) values ('Bahamas', 'BS');
insert into countries (country_name, iso_c_code) values ('Bahrain', 'BH');
insert into countries (country_name, iso_c_code) values ('Bangladesh', 'BD');
insert into countries (country_name, iso_c_code) values ('Barbados', 'BB');
insert into countries (country_name, iso_c_code) values ('Belarus', 'BY');
insert into countries (country_name, iso_c_code) values ('Belgium', 'BE');
insert into countries (country_name, iso_c_code) values ('Belize', 'BZ');
insert into countries (country_name, iso_c_code) values ('Benin', 'BJ');
insert into countries (country_name, iso_c_code) values ('Bermuda', 'BM');
insert into countries (country_name, iso_c_code) values ('Bhutan', 'BT');
insert into countries (country_name, iso_c_code) values ('Bolivia (Plurinational State of)', 'BO');
insert into countries (country_name, iso_c_code) values ('Bonaire Sint Eustatius and Saba', 'BQ');
insert into countries (country_name, iso_c_code) values ('Bosnia and Herzegovina', 'BA');
insert into countries (country_name, iso_c_code) values ('Botswana', 'BW');
insert into countries (country_name, iso_c_code) values ('Bouvet Island', 'BV');
insert into countries (country_name, iso_c_code) values ('Brazil', 'BR');
insert into countries (country_name, iso_c_code) values ('British Indian Ocean Territory', 'IO');
insert into countries (country_name, iso_c_code) values ('Brunei Darussalam', 'BN');
insert into countries (country_name, iso_c_code) values ('Bulgaria', 'BG');
insert into countries (country_name, iso_c_code) values ('Burkina Faso', 'BF');
insert into countries (country_name, iso_c_code) values ('Burundi', 'BI');
insert into countries (country_name, iso_c_code) values ('Cabo Verde', 'CV');
insert into countries (country_name, iso_c_code) values ('Cambodia', 'KH');
insert into countries (country_name, iso_c_code) values ('Cameroon', 'CM');
insert into countries (country_name, iso_c_code) values ('Canada', 'CA');
insert into countries (country_name, iso_c_code) values ('Cayman Islands', 'KY');
insert into countries (country_name, iso_c_code) values ('Central African Republic', 'CF');
insert into countries (country_name, iso_c_code) values ('Chad', 'TD');
insert into countries (country_name, iso_c_code) values ('Chile', 'CL');
insert into countries (country_name, iso_c_code) values ('China', 'CN');
insert into countries (country_name, iso_c_code) values ('Christmas Island', 'CX');
insert into countries (country_name, iso_c_code) values ('Cocos (Keeling) Islands', 'CC');
insert into countries (country_name, iso_c_code) values ('Colombia', 'CO');
insert into countries (country_name, iso_c_code) values ('Comoros', 'KM');
insert into countries (country_name, iso_c_code) values ('Congo', 'CG');
insert into countries (country_name, iso_c_code) values ('Congo Democratic Republic of the', 'CD');
insert into countries (country_name, iso_c_code) values ('Cook Islands', 'CK');
insert into countries (country_name, iso_c_code) values ('Costa Rica', 'CR');
insert into countries (country_name, iso_c_code) values ('Côte d''Ivoire', 'CI');
insert into countries (country_name, iso_c_code) values ('Croatia', 'HR');
insert into countries (country_name, iso_c_code) values ('Cuba', 'CU');
insert into countries (country_name, iso_c_code) values ('Curaçao', 'CW');
insert into countries (country_name, iso_c_code) values ('Cyprus', 'CY');
insert into countries (country_name, iso_c_code) values ('Czechia', 'CZ');
insert into countries (country_name, iso_c_code) values ('Denmark', 'DK');
insert into countries (country_name, iso_c_code) values ('Djibouti', 'DJ');
insert into countries (country_name, iso_c_code) values ('Dominica', 'DM');
insert into countries (country_name, iso_c_code) values ('Dominican Republic', 'DO');
insert into countries (country_name, iso_c_code) values ('Ecuador', 'EC');
insert into countries (country_name, iso_c_code) values ('Egypt', 'EG');
insert into countries (country_name, iso_c_code) values ('El Salvador', 'SV');
insert into countries (country_name, iso_c_code) values ('Equatorial Guinea', 'GQ');
insert into countries (country_name, iso_c_code) values ('Eritrea', 'ER');
insert into countries (country_name, iso_c_code) values ('Estonia', 'EE');
insert into countries (country_name, iso_c_code) values ('Eswatini', 'SZ');
insert into countries (country_name, iso_c_code) values ('Ethiopia', 'ET');
insert into countries (country_name, iso_c_code) values ('Falkland Islands (Malvinas)', 'FK');
insert into countries (country_name, iso_c_code) values ('Faroe Islands', 'FO');
insert into countries (country_name, iso_c_code) values ('Fiji', 'FJ');
insert into countries (country_name, iso_c_code) values ('Finland', 'FI');
insert into countries (country_name, iso_c_code) values ('France', 'FR');
insert into countries (country_name, iso_c_code) values ('French Guiana', 'GF');
insert into countries (country_name, iso_c_code) values ('French Polynesia', 'PF');
insert into countries (country_name, iso_c_code) values ('French Southern Territories', 'TF');
insert into countries (country_name, iso_c_code) values ('Gabon', 'GA');
insert into countries (country_name, iso_c_code) values ('Gambia', 'GM');
insert into countries (country_name, iso_c_code) values ('Georgia', 'GE');
insert into countries (country_name, iso_c_code) values ('Germany', 'DE');
insert into countries (country_name, iso_c_code) values ('Ghana', 'GH');
insert into countries (country_name, iso_c_code) values ('Gibraltar', 'GI');
insert into countries (country_name, iso_c_code) values ('Greece', 'GR');
insert into countries (country_name, iso_c_code) values ('Greenland', 'GL');
insert into countries (country_name, iso_c_code) values ('Grenada', 'GD');
insert into countries (country_name, iso_c_code) values ('Guadeloupe', 'GP');
insert into countries (country_name, iso_c_code) values ('Guam', 'GU');
insert into countries (country_name, iso_c_code) values ('Guatemala', 'GT');
insert into countries (country_name, iso_c_code) values ('Guernsey', 'GG');
insert into countries (country_name, iso_c_code) values ('Guinea', 'GN');
insert into countries (country_name, iso_c_code) values ('Guinea-Bissau', 'GW');
insert into countries (country_name, iso_c_code) values ('Guyana', 'GY');
insert into countries (country_name, iso_c_code) values ('Haiti', 'HT');
insert into countries (country_name, iso_c_code) values ('Heard Island and McDonald Islands', 'HM');
insert into countries (country_name, iso_c_code) values ('Holy See', 'VA');
insert into countries (country_name, iso_c_code) values ('Honduras', 'HN');
insert into countries (country_name, iso_c_code) values ('Hong Kong', 'HK');
insert into countries (country_name, iso_c_code) values ('Hungary', 'HU');
insert into countries (country_name, iso_c_code) values ('Iceland', 'IS');
insert into countries (country_name, iso_c_code) values ('India', 'IN');
insert into countries (country_name, iso_c_code) values ('Indonesia', 'ID');
insert into countries (country_name, iso_c_code) values ('Iran (Islamic Republic of)', 'IR');
insert into countries (country_name, iso_c_code) values ('Iraq', 'IQ');
insert into countries (country_name, iso_c_code) values ('Ireland', 'IE');
insert into countries (country_name, iso_c_code) values ('Isle of Man', 'IM');
insert into countries (country_name, iso_c_code) values ('Israel', 'IL');
insert into countries (country_name, iso_c_code) values ('Italy', 'IT');
insert into countries (country_name, iso_c_code) values ('Jamaica', 'JM');
insert into countries (country_name, iso_c_code) values ('Japan', 'JP');
insert into countries (country_name, iso_c_code) values ('Jersey', 'JE');
insert into countries (country_name, iso_c_code) values ('Jordan', 'JO');
insert into countries (country_name, iso_c_code) values ('Kazakhstan', 'KZ');
insert into countries (country_name, iso_c_code) values ('Kenya', 'KE');
insert into countries (country_name, iso_c_code) values ('Kiribati', 'KI');
insert into countries (country_name, iso_c_code) values ('Korea (Democratic People''s Republic of)', 'KP');
insert into countries (country_name, iso_c_code) values ('Korea Republic of', 'KR');
insert into countries (country_name, iso_c_code) values ('Kuwait', 'KW');
insert into countries (country_name, iso_c_code) values ('Kyrgyzstan', 'KG');
insert into countries (country_name, iso_c_code) values ('Lao People''s Democratic Republic', 'LA');
insert into countries (country_name, iso_c_code) values ('Latvia', 'LV');
insert into countries (country_name, iso_c_code) values ('Lebanon', 'LB');
insert into countries (country_name, iso_c_code) values ('Lesotho', 'LS');
insert into countries (country_name, iso_c_code) values ('Liberia', 'LR');
insert into countries (country_name, iso_c_code) values ('Libya', 'LY');
insert into countries (country_name, iso_c_code) values ('Liechtenstein', 'LI');
insert into countries (country_name, iso_c_code) values ('Lithuania', 'LT');
insert into countries (country_name, iso_c_code) values ('Luxembourg', 'LU');
insert into countries (country_name, iso_c_code) values ('Macao', 'MO');
insert into countries (country_name, iso_c_code) values ('Madagascar', 'MG');
insert into countries (country_name, iso_c_code) values ('Malawi', 'MW');
insert into countries (country_name, iso_c_code) values ('Malaysia', 'MY');
insert into countries (country_name, iso_c_code) values ('Maldives', 'MV');
insert into countries (country_name, iso_c_code) values ('Mali', 'ML');
insert into countries (country_name, iso_c_code) values ('Malta', 'MT');
insert into countries (country_name, iso_c_code) values ('Marshall Islands', 'MH');
insert into countries (country_name, iso_c_code) values ('Martinique', 'MQ');
insert into countries (country_name, iso_c_code) values ('Mauritania', 'MR');
insert into countries (country_name, iso_c_code) values ('Mauritius', 'MU');
insert into countries (country_name, iso_c_code) values ('Mayotte', 'YT');
insert into countries (country_name, iso_c_code) values ('Mexico', 'MX');
insert into countries (country_name, iso_c_code) values ('Micronesia (Federated States of)', 'FM');
insert into countries (country_name, iso_c_code) values ('Moldova Republic of', 'MD');
insert into countries (country_name, iso_c_code) values ('Monaco', 'MC');
insert into countries (country_name, iso_c_code) values ('Mongolia', 'MN');
insert into countries (country_name, iso_c_code) values ('Montenegro', 'ME');
insert into countries (country_name, iso_c_code) values ('Montserrat', 'MS');
insert into countries (country_name, iso_c_code) values ('Morocco', 'MA');
insert into countries (country_name, iso_c_code) values ('Mozambique', 'MZ');
insert into countries (country_name, iso_c_code) values ('Myanmar', 'MM');
insert into countries (country_name, iso_c_code) values ('Namibia', 'NA');
insert into countries (country_name, iso_c_code) values ('Nauru', 'NR');
insert into countries (country_name, iso_c_code) values ('Nepal', 'NP');
insert into countries (country_name, iso_c_code) values ('Netherlands', 'NL');
insert into countries (country_name, iso_c_code) values ('New Caledonia', 'NC');
insert into countries (country_name, iso_c_code) values ('New Zealand', 'NZ');
insert into countries (country_name, iso_c_code) values ('Nicaragua', 'NI');
insert into countries (country_name, iso_c_code) values ('Niger', 'NE');
insert into countries (country_name, iso_c_code) values ('Nigeria', 'NG');
insert into countries (country_name, iso_c_code) values ('Niue', 'NU');
insert into countries (country_name, iso_c_code) values ('Norfolk Island', 'NF');
insert into countries (country_name, iso_c_code) values ('North Macedonia', 'MK');
insert into countries (country_name, iso_c_code) values ('Northern Mariana Islands', 'MP');
insert into countries (country_name, iso_c_code) values ('Norway', 'NO');
insert into countries (country_name, iso_c_code) values ('Oman', 'OM');
insert into countries (country_name, iso_c_code) values ('Pakistan', 'PK');
insert into countries (country_name, iso_c_code) values ('Palau', 'PW');
insert into countries (country_name, iso_c_code) values ('Palestine State of', 'PS');
insert into countries (country_name, iso_c_code) values ('Panama', 'PA');
insert into countries (country_name, iso_c_code) values ('Papua New Guinea', 'PG');
insert into countries (country_name, iso_c_code) values ('Paraguay', 'PY');
insert into countries (country_name, iso_c_code) values ('Peru', 'PE');
insert into countries (country_name, iso_c_code) values ('Philippines', 'PH');
insert into countries (country_name, iso_c_code) values ('Pitcairn', 'PN');
insert into countries (country_name, iso_c_code) values ('Poland', 'PL');
insert into countries (country_name, iso_c_code) values ('Portugal', 'PT');
insert into countries (country_name, iso_c_code) values ('Puerto Rico', 'PR');
insert into countries (country_name, iso_c_code) values ('Qatar', 'QA');
insert into countries (country_name, iso_c_code) values ('Réunion', 'RE');
insert into countries (country_name, iso_c_code) values ('Romania', 'RO');
insert into countries (country_name, iso_c_code) values ('Russian Federation', 'RU');
insert into countries (country_name, iso_c_code) values ('Rwanda', 'RW');
insert into countries (country_name, iso_c_code) values ('Saint Barthélemy', 'BL');
insert into countries (country_name, iso_c_code) values ('Saint Helena Ascension and Tristan da Cunha', 'SH');
insert into countries (country_name, iso_c_code) values ('Saint Kitts and Nevis', 'KN');
insert into countries (country_name, iso_c_code) values ('Saint Lucia', 'LC');
insert into countries (country_name, iso_c_code) values ('Saint Martin (French part)', 'MF');
insert into countries (country_name, iso_c_code) values ('Saint Pierre and Miquelon', 'PM');
insert into countries (country_name, iso_c_code) values ('Saint Vincent and the Grenadines', 'VC');
insert into countries (country_name, iso_c_code) values ('Samoa', 'WS');
insert into countries (country_name, iso_c_code) values ('San Marino', 'SM');
insert into countries (country_name, iso_c_code) values ('Sao Tome and Principe', 'ST');
insert into countries (country_name, iso_c_code) values ('Saudi Arabia', 'SA');
insert into countries (country_name, iso_c_code) values ('Senegal', 'SN');
insert into countries (country_name, iso_c_code) values ('Serbia', 'RS');
insert into countries (country_name, iso_c_code) values ('Seychelles', 'SC');
insert into countries (country_name, iso_c_code) values ('Sierra Leone', 'SL');
insert into countries (country_name, iso_c_code) values ('Singapore', 'SG');
insert into countries (country_name, iso_c_code) values ('Sint Maarten (Dutch part)', 'SX');
insert into countries (country_name, iso_c_code) values ('Slovakia', 'SK');
insert into countries (country_name, iso_c_code) values ('Slovenia', 'SI');
insert into countries (country_name, iso_c_code) values ('Solomon Islands', 'SB');
insert into countries (country_name, iso_c_code) values ('Somalia', 'SO');
insert into countries (country_name, iso_c_code) values ('South Africa', 'ZA');
insert into countries (country_name, iso_c_code) values ('South Georgia and the South Sandwich Islands', 'GS');
insert into countries (country_name, iso_c_code) values ('South Sudan', 'SS');
insert into countries (country_name, iso_c_code) values ('Spain', 'ES');
insert into countries (country_name, iso_c_code) values ('Sri Lanka', 'LK');
insert into countries (country_name, iso_c_code) values ('Sudan', 'SD');
insert into countries (country_name, iso_c_code) values ('Suriname', 'SR');
insert into countries (country_name, iso_c_code) values ('Svalbard and Jan Mayen', 'SJ');
insert into countries (country_name, iso_c_code) values ('Sweden', 'SE');
insert into countries (country_name, iso_c_code) values ('Switzerland', 'CH');
insert into countries (country_name, iso_c_code) values ('Syrian Arab Republic', 'SY');
insert into countries (country_name, iso_c_code) values ('Taiwan Province of China', 'TW');
insert into countries (country_name, iso_c_code) values ('Tajikistan', 'TJ');
insert into countries (country_name, iso_c_code) values ('Tanzania United Republic of', 'TZ');
insert into countries (country_name, iso_c_code) values ('Thailand', 'TH');
insert into countries (country_name, iso_c_code) values ('Timor-Leste', 'TL');
insert into countries (country_name, iso_c_code) values ('Togo', 'TG');
insert into countries (country_name, iso_c_code) values ('Tokelau', 'TK');
insert into countries (country_name, iso_c_code) values ('Tonga', 'TO');
insert into countries (country_name, iso_c_code) values ('Trinidad and Tobago', 'TT');
insert into countries (country_name, iso_c_code) values ('Tunisia', 'TN');
insert into countries (country_name, iso_c_code) values ('Turkey', 'TR');
insert into countries (country_name, iso_c_code) values ('Turkmenistan', 'TM');
insert into countries (country_name, iso_c_code) values ('Turks and Caicos Islands', 'TC');
insert into countries (country_name, iso_c_code) values ('Tuvalu', 'TV');
insert into countries (country_name, iso_c_code) values ('Uganda', 'UG');
insert into countries (country_name, iso_c_code) values ('Ukraine', 'UA');
insert into countries (country_name, iso_c_code) values ('United Arab Emirates', 'AE');
insert into countries (country_name, iso_c_code) values ('United Kingdom of Great Britain and Northern Ireland', 'GB');
insert into countries (country_name, iso_c_code) values ('United States of America', 'US');
insert into countries (country_name, iso_c_code) values ('United States Minor Outlying Islands', 'UM');
insert into countries (country_name, iso_c_code) values ('Uruguay', 'UY');
insert into countries (country_name, iso_c_code) values ('Uzbekistan', 'UZ');
insert into countries (country_name, iso_c_code) values ('Vanuatu', 'VU');
insert into countries (country_name, iso_c_code) values ('Venezuela (Bolivarian Republic of)', 'VE');
insert into countries (country_name, iso_c_code) values ('Viet Nam', 'VN');
insert into countries (country_name, iso_c_code) values ('Virgin Islands (British)', 'VG');
insert into countries (country_name, iso_c_code) values ('Virgin Islands (U.S.)', 'VI');
insert into countries (country_name, iso_c_code) values ('Wallis and Futuna', 'WF');
insert into countries (country_name, iso_c_code) values ('Western Sahara', 'EH');
insert into countries (country_name, iso_c_code) values ('Yemen', 'YE');
insert into countries (country_name, iso_c_code) values ('Zambia', 'ZM');
insert into countries (country_name, iso_c_code) values ('Zimbabwe', 'ZW');
