create table rooms (
	id INT NOT NULL PRIMARY KEY,
	acc_shortname VARCHAR(4) NOT NULL REFERENCES accomodation_types(acc_shortname),
	rnumber VARCHAR(50),
	rdescript TEXT
);
insert into rooms (id, acc_shortname, rnumber, rdescript) values (1, 'cot', '84-112-8389', 'maecenas leo odio condimentum');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (2, 'iso', '49-624-1612', 'vestibulum ac est lacinia nisi venenatis tristique fusce congue');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (3, 'cot', '64-969-6920', 'euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (4, 'perh', '21-640-5924', 'quis augue luctus tincidunt nulla mollis molestie lorem quisque');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (5, 'iso', '62-140-5913', 'luctus ultricies eu nibh quisque id justo');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (6, 'sup', '44-581-6138', 'nulla quisque arcu libero rutrum ac lobortis');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (7, 'cot', '35-719-9298', 'venenatis lacinia aenean sit amet justo morbi ut odio cras');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (8, 'iso', '16-787-8377', 'luctus et ultrices posuere');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (9, 'perh', '87-678-7099', 'dui nec nisi volutpat eleifend donec');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (10, 'sup', '67-176-4855', 'sem duis aliquam convallis nunc proin at turpis a pede');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (11, 'eco', '49-640-1217', 'felis eu sapien cursus vestibulum proin eu mi');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (12, 'sup', '24-987-6559', 'rhoncus dui vel sem');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (13, 'iso', '12-522-8439', 'aliquet at feugiat non pretium quis lectus suspendisse');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (14, 'eco', '69-660-9043', 'sed tristique in tempus sit amet sem fusce consequat nulla');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (15, 'iso', '67-804-1037', 'ullamcorper augue a suscipit nulla elit ac nulla sed');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (16, 'iso', '07-221-7433', 'platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (17, 'perh', '51-191-7687', 'rutrum ac lobortis vel dapibus at diam nam tristique tortor');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (18, 'sup', '38-667-3354', 'id justo sit amet');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (19, 'eco', '57-220-5414', 'consectetuer eget rutrum at lorem integer');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (20, 'cot', '83-354-1630', 'hac habitasse platea dictumst morbi vestibulum velit id pretium');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (21, 'iso', '24-707-3146', 'dui vel nisl duis ac nibh fusce');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (22, 'perh', '63-298-7510', 'mi sit amet lobortis sapien');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (23, 'eco', '09-866-4867', 'orci pede venenatis non sodales sed tincidunt');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (24, 'eco', '81-428-2937', 'augue vel accumsan tellus nisi eu');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (25, 'eco', '09-375-5489', 'blandit mi in porttitor pede justo eu massa');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (26, 'iso', '68-742-2879', 'sem duis aliquam convallis nunc proin at turpis a pede');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (27, 'perh', '70-759-4419', 'dis parturient montes nascetur');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (28, 'iso', '17-046-7727', 'in felis eu sapien');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (29, 'eco', '80-431-7517', 'aliquam non mauris morbi non lectus aliquam sit amet');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (30, 'eco', '28-432-4838', 'consequat nulla nisl nunc nisl duis bibendum');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (31, 'eco', '88-054-5997', 'at nunc commodo placerat praesent blandit nam');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (32, 'perh', '10-465-5085', 'nisi nam ultrices libero');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (33, 'sup', '93-563-6038', 'sapien arcu sed augue aliquam erat volutpat');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (34, 'eco', '89-337-7778', 'tellus in sagittis dui vel nisl duis ac nibh');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (35, 'sup', '36-034-4657', 'etiam faucibus cursus urna ut tellus nulla ut erat id');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (36, 'perh', '17-401-4484', 'ante ipsum primis in');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (37, 'perh', '08-406-7624', 'dapibus duis at velit eu est congue elementum in');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (38, 'iso', '98-157-2606', 'felis fusce posuere felis sed lacus morbi');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (39, 'eco', '99-550-0890', 'semper rutrum nulla nunc purus phasellus');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (40, 'perh', '26-882-2760', 'augue quam sollicitudin vitae consectetuer');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (41, 'perh', '90-007-2925', 'donec ut dolor morbi vel lectus');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (42, 'iso', '36-714-2159', 'amet lobortis sapien sapien non mi integer ac neque');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (43, 'perh', '71-444-3517', 'curae nulla dapibus dolor vel est donec odio justo');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (44, 'cot', '16-309-7570', 'vulputate luctus cum sociis natoque penatibus et');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (45, 'cot', '82-533-1904', 'rutrum rutrum neque aenean auctor');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (46, 'eco', '63-985-6116', 'ante vivamus tortor duis mattis egestas metus');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (47, 'eco', '57-607-1950', 'diam erat fermentum justo nec condimentum neque sapien placerat');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (48, 'perh', '13-757-8986', 'natoque penatibus et magnis dis parturient montes');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (49, 'eco', '60-749-5025', 'ac diam cras pellentesque volutpat');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (50, 'perh', '91-896-7184', 'dapibus nulla suscipit ligula in lacus curabitur at ipsum');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (51, 'sup', '44-553-9895', 'amet lobortis sapien sapien non mi integer ac neque duis');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (52, 'eco', '83-043-2880', 'luctus et ultrices posuere');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (53, 'iso', '27-354-5720', 'congue etiam justo etiam pretium');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (54, 'sup', '49-255-6886', 'etiam justo etiam pretium iaculis');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (55, 'iso', '90-778-3783', 'velit donec diam neque vestibulum eget vulputate');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (56, 'iso', '13-585-7400', 'ornare consequat lectus in est risus auctor sed tristique');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (57, 'sup', '36-902-1813', 'erat volutpat in congue etiam justo');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (58, 'iso', '12-717-2532', 'lacus morbi sem mauris laoreet ut rhoncus aliquet');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (59, 'iso', '54-226-9546', 'id luctus nec molestie sed justo');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (60, 'sup', '90-645-9743', 'aliquet pulvinar sed nisl nunc rhoncus dui');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (61, 'eco', '95-416-6281', 'quam pede lobortis ligula sit amet eleifend pede');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (62, 'iso', '90-927-1122', 'penatibus et magnis dis');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (63, 'perh', '11-153-6640', 'gravida nisi at nibh');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (64, 'iso', '92-321-0616', 'potenti in eleifend quam a odio in');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (65, 'iso', '54-979-1121', 'non velit donec diam neque vestibulum');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (66, 'iso', '01-816-9476', 'magnis dis parturient montes nascetur ridiculus mus etiam vel');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (67, 'cot', '93-821-3215', 'morbi porttitor lorem id ligula');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (68, 'sup', '30-626-4800', 'sapien sapien non mi integer ac neque');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (69, 'perh', '30-007-5788', 'eu magna vulputate luctus cum sociis');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (70, 'cot', '34-147-7518', 'suscipit a feugiat et');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (71, 'sup', '22-216-5010', 'mattis odio donec vitae nisi nam ultrices libero non');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (72, 'perh', '05-050-5845', 'donec pharetra magna vestibulum aliquet ultrices erat tortor');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (73, 'perh', '70-729-4517', 'dui luctus rutrum nulla tellus');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (74, 'iso', '16-777-1457', 'diam in magna bibendum imperdiet nullam orci pede venenatis non');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (75, 'sup', '69-255-0723', 'vel dapibus at diam nam tristique tortor eu pede');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (76, 'sup', '91-673-5711', 'adipiscing elit proin interdum mauris non');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (77, 'iso', '46-436-5476', 'justo sollicitudin ut suscipit a feugiat et eros vestibulum ac');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (78, 'perh', '69-397-9053', 'odio justo sollicitudin ut suscipit a feugiat');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (79, 'iso', '08-748-2770', 'ipsum ac tellus semper interdum mauris ullamcorper purus');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (80, 'eco', '92-353-7822', 'sapien a libero nam dui');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (81, 'eco', '47-845-3044', 'sapien a libero nam dui proin leo');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (82, 'cot', '65-952-9197', 'erat curabitur gravida nisi at');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (83, 'cot', '51-572-1593', 'ligula in lacus curabitur');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (84, 'iso', '13-405-5282', 'id luctus nec molestie sed justo pellentesque');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (85, 'cot', '33-793-3290', 'eleifend pede libero quis');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (86, 'perh', '55-360-7851', 'enim leo rhoncus sed vestibulum sit amet');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (87, 'eco', '25-585-7614', 'posuere cubilia curae nulla dapibus dolor');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (88, 'iso', '25-908-6204', 'ante ipsum primis in faucibus orci');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (89, 'cot', '19-076-9131', 'ultrices vel augue vestibulum ante');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (90, 'eco', '52-425-0778', 'quis justo maecenas rhoncus aliquam');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (91, 'iso', '02-107-7194', 'congue vivamus metus arcu adipiscing molestie hendrerit');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (92, 'eco', '45-373-1134', 'mauris sit amet eros suspendisse accumsan tortor quis turpis sed');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (93, 'iso', '77-778-7446', 'ante ipsum primis in faucibus orci luctus et');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (94, 'sup', '50-178-5632', 'lectus aliquam sit amet diam in magna bibendum imperdiet');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (95, 'sup', '52-919-4482', 'tellus semper interdum mauris ullamcorper');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (96, 'eco', '70-263-5211', 'congue risus semper porta volutpat');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (97, 'iso', '48-885-8835', 'odio curabitur convallis duis consequat dui nec');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (98, 'iso', '44-546-6770', 'mi sit amet lobortis');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (99, 'perh', '62-653-9519', 'vivamus vel nulla eget eros elementum');
insert into rooms (id, acc_shortname, rnumber, rdescript) values (100, 'cot', '39-368-4429', 'lacinia sapien quis libero nullam sit amet');
